---
title: "VR on T cell populations expanding in response to COVID vaccination"
author: "Claire Cross"
date: "2026-07-01"
---

#COVID vaccine dataset downloaded from: https://flowrepository.org/experiments/4853 
Kramer, K. J., E. M. Wilfong, K. Voss, S. M. Barone, A. R. Shiakolas, N. Raju, C. E. Roe, N. Suryadevara, L. M. Walker, S. C. Wall, A. Paulo, S. Schaefer, D. Dahunsi, C. S. Westlake, J. E. Crowe, Jr., R. H. Carnahan, J. C. Rathmell, R. H. Bonami, I. S. Georgiev, and J. M. Irish. 2022. 'Single-cell profiling of the antigen-specific response to BNT162b2 SARS-CoV-2 RNA vaccine', Nat Commun, 13: 3466. https://doi.org/10.1038/s41467-022-31142-5. 

```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE)

# # uncomment lines below to install packages
# if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
# BiocManager::install("Biobase")
# BiocManager::install("flowCore")
# BiocManager::install("cytoMEM")
# install.packages("ggplot2", repos = "http://cran.us.r-project.org")
# install.packages("tidyverse", repos = "http://cran.us.r-project.org")
# install.packages("cowplot", repos = "http://cran.us.r-project.org")
# install.packages("RColorBrewer", repos = "http://cran.us.r-project.org")
# #install.packages("viridis", repos = "http://cran.us.r-project.org")
# install.packages("stringr", repos = "http://cran.us.r-project.org")
# install.packages("FNN", repos = "http://cran.us.r-project.org")
# install.packages("matrixStats", repos = "http://cran.us.r-project.org")
# install.packages("scales", repos = "http://cran.us.r-project.org")
```

```{r initialization}
#load packages into the working library
suppressPackageStartupMessages({library(Biobase)
  library(flowCore)
  library(cytoMEM)
  library(ggplot2)
  library(tidyverse)
  library(cowplot)
  library(RColorBrewer)
  library(viridis)
  library(stringr)
  library(FNN)
  library(matrixStats)
  library(scales)})
source("./R/general_plots.R")
source("./R/VR-Eye_functions.R")
source("./R/VR-Eye_plots.R")
source('./R/tatarize_color_palette.R')
source('./R/VR-Eye_support_functions.R')
expr.colors = colorRampPalette(rev(brewer.pal(n = 11, name = "Spectral")))(5)

#specify fcs file location and output path
file.path <- paste0(getwd(),"/data files/COVID vaccine/")
og.output.path <- paste0(getwd(), '/output files/COVID vaccine/')

#locate fcs file
fcs.files <- dir(path = file.path, pattern = "*.fcs")
print(fcs.files)

#KNN settings
kvalue <- 60

#do you wish to downsample the data?
sample.files <- FALSE
sample.num <- 1000 
```

```{r load data}
setwd(file.path)
#read each file in fcs.files and combine all data into one dataframe
data.lists <- lapply(lapply(fcs.files, read.FCS, truncate_max_range = FALSE), exprs)
combined.data <- as.data.frame(do.call(rbind, mapply(cbind, data.lists, "File_ID" = c(1:length(data.lists)), SIMPLIFY = F)))
colnames(combined.data)[1:(length(combined.data) - 3)] <- as.character(read.FCS(fcs.files[[1]])@parameters@data[["desc"]])

print(colnames(combined.data))
```

```{r downsampling}
if (sample.files == TRUE){ 
  #set seed for reproducibility
  set.seed(1)
  #split into individual files
  files.to.sample <- split(combined.data, combined.data$`File_ID`) 
  sampled.data <- list()
  for (i in 1:length(files.to.sample)){
    #file has a lot of cells => we must downsample
    if ((nrow(files.to.sample[[i]])) >= sample.num){ 
      sampled.data[[i]] <- as.data.frame(files.to.sample[[i]][sample(nrow(files.to.sample[[i]]), sample.num), ])
    #not enough cells to downsample => just keep all of the cells present
    }else{sampled.data[[i]] <- files.to.sample[[i]]}
  }
  #combine list data into one big data frame
  combined.sampled.data <- as.data.frame(do.call(rbind, sampled.data))
}else{combined.sampled.data <- combined.data}

print(paste0(nrow(combined.sampled.data), ' cells will be analyzed'))
```

```{r select data}
#select tSNE columns 
tSNE.indx1 <- 77
tSNE.indx2 <- 78
tSNE.data <- combined.sampled.data[, c(tSNE.indx1:tSNE.indx2)]
colnames(tSNE.data) <- c("tSNE1", "tSNE2")

#select marker channels
panel.info <- marker.selection(colnames(combined.sampled.data), token='_', position='after')
marker.data <- combined.sampled.data[,panel.info$indices]
colnames(marker.data) <- panel.info$trimmed_names

#arcsinh transformation
cofactors <- c(45, 15, 10, 10, 10, 15, 5, 15, 25, 25, 
               15, 15, 15, 15, 15, 15, 15, 25, 25, 15, 
               15, 15, 25, 15, 25, 25, 15, 15, 45, 15, 
               15, 15, 45, 25, 25, 15, 25, 25, 15, 25)
panel.info$cofactors <- cofactors
marker.data <- asinh(marker.data/cofactors)
print(colnames(marker.data))
```

```{r t-SNE plots}
#plot tSNE axes
tsne.plot <- ggplot(tSNE.data) + geom_point(aes(x=tSNE1, y=tSNE2), color='lightgrey') +
              labs(x='t-SNE1', y='t-SNE2', title='COVID Vaccine Dataset',
                   caption="Data from Kramer, Wilfong, and Voss et al., Nat Commun, 2022") +
              coord_fixed(ratio=1) + theme_bw() + theme(panel.grid = element_blank())
print(tsne.plot)

#plot cell density on t-SNE axes
tsne.dens.plot <- tsne_density(tSNE.data, orientation=1, capt="Data from Data from Kramer, Wilfong, and Voss et al., Nat Commun, 2022",
                               export=TRUE, output_path=og.output.path)

#plot heat on markers
tsne.heat.on.markers <- tsne_heat_on_markers(tSNE.data, marker.data, n_col=8, orientation=1,
                                             export=TRUE, output_path=og.output.path)
```

```{r KNN MEM}
output.path <- og.output.path
dir.create(output.path)

#look for existing KNN labels file
knn.path <- paste0(getwd(), '/output files/')
setwd(knn.path)
knn.data.file <- dir(pattern='knn labels.RData')
rds.name <- paste0(knn.path, 'knn labels.RData')
  
#load knn.labels if the file exists; otherwise, calculate knn.labels
if(is.na(knn.data.file[1])){
  start_time = Sys.time()
  knn.labels = knn_MEM(tSNE.data, marker.data, kvalue=kvalue)
  total_time = Sys.time() - start_time
  print(' KNN MEM completed in ')
  print(total_time)
    
  #save as rds 
  save(knn.labels, file = paste0(og.output.path, 'knn labels.RData'))
}else{load(file=rds.name)}
```

```{r set VR searching info}
#specify searching labels 
goals <- c('CD38+ICOS+MemoryCD8_40features', 'CD38+ICOS+MemoryCD8_17features', 'CD38+ICOS+MemoryCD8_4features')
ref.labels <- c(
  #40 features
  'CD38+10 CD44+8 ICOS+7 CD45+6 CD8+6 CD45R0+6 CD27+5 CXCR3+4 GLUT1+4 CD95+4 PD-1+4 CPT1a+3 Ki-67+3 HLA-DR+3 CD3+2 CD98+2 CTLA4+2 ATP5a+1 GLUT3+1 CYTOC+1 CD45RA+1 CXCR4+1 CD66b+0 CD16+0 CD14+0 CD4+0 CD19+0 CD127+0 GRIM19+0 CD20+0 CCR4+0 CD134+0 TCRgd+0 CD137+0 CCR7+0 CD25+0 CXCR5+0 CD57+0 CD56+0 CD11b+0', 
  #17 features
  'CD38+10 ICOS+7 CD8+6 CD45R0+6 CXCR3+4 CD95+4 PD-1+4 CPT1a+3 Ki-67+3 HLA-DR+3 CD3+2 CYTOC+1 CD45RA+1 CXCR4+1 CD4+0 CD127+0 CCR7+0',
  #4 features
  'CD38+10 CD45RA+1 CD4+0 CCR7+0'
)
```

```{r, VR}
#set multi-round variables
current_round <- 0 
multi.labels <- data.frame()
multi.df <- combined.sampled.data

#search for each ref label supplied
for (j in 1:length(goals)){
  #get goal & search label
  goal <- goals[j]
  ref.label <- ref.labels[j]
  print(paste0('searching for ', goal, ': ', ref.label))

  # check that markers in the searching label are being measured in the new dataset
  common.label <- check_panel(ref.label, panel.info)
  common.ref.MEM.score <- common.label[[1]]
  ref.label <- common.label[[2]]

  # create output folder
  current_round <- current_round + 1
  run.folder <- paste0(og.output.path, goal, '/')
  dir.create(run.folder)

  #VR search and sim plot
  common.MEM.scores <- knn.labels[, colnames(common.ref.MEM.score)]

  #check if only one marker
  if (!is.data.frame(common.MEM.scores)) {
    common.MEM.scores <- as.data.frame(common.MEM.scores)
    colnames(common.MEM.scores) <- colnames(common.ref.MEM.score)
  }
    
  #calculate similarity
  print('calculating similarity')
  sim <- sim_scores(common.MEM.scores, common.ref.MEM.score)
  my.range <- max(sim)-min(sim)
  sim.data <- cbind(marker.data, File_ID=multi.df$File_ID, tSNE.data, sim)
  sim.plot <- VR_Eye_sim_plot(sim.data, ref.label)
  #export
  png(paste0(run.folder, goal, " similarity.png"),
      height = 1500, width = 1500, res = 200)
  print(sim.plot)
  dev.off()

  #save round information to multi.df
  print('saving data to multi.df')
  this.round <- c()
  this.round = cbind(
    VRPTR_round = current_round,
    search_label = ref.label,
    goal = goal,
    kvalue = kvalue
  )
  multi.labels <- rbind(multi.labels, this.round)
  save(multi.labels, file = paste0(og.output.path, "multi-run labels.RData"))

  #save similarity score in multi-round results df
  multi.df <- cbind(multi.df, sim)
  colnames(multi.df)[ncol(multi.df)] <- paste0("r", current_round, "_", goal, "_sim")

  #update multi.df
  rds.name <- paste0(og.output.path, 'multi-run VR.RData')
  save(multi.df, file = rds.name)
}
```

```{r export as fcs}
#split data by patient
separate.fcs.files <- split(multi.df, multi.df$File_ID)
for (i in 1:length(separate.fcs.files)){
  #format data
  reduce.data <- separate.fcs.files[[i]]
  mat.input <- as.matrix(reduce.data)
  #set metadata
  metadata <- data.frame(name=dimnames(mat.input)[[2]], desc=colnames(multi.df))
  metadata$range <- apply(apply(mat.input, 2, range), 2, diff)
  metadata$minRange <- apply(mat.input, 2, min)
  metadata$maxRange <- apply(mat.input, 2, max)
  input.flowframe <- new("flowFrame", exprs=mat.input, parameters = AnnotatedDataFrame(metadata))  
  #write file
  sample.name <- str_remove(fcs.files[i], '.fcs')
  new.filename <- paste0(og.output.path, strftime(Sys.time(),"%Y-%m-%d"), "_", sample.name, "_VR.fcs")
  write.FCS(input.flowframe, filename=new.filename)
  print(paste0("FCS file ", i, ': ', sample.name, " done"))
}
```


